#line 1 "sample.flex.cpp"

#line 3 "sample.flex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext

#include "FlexLexer.h"

inline int yyFlexLexer::yywrap() { return 1; }

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 129
#define YY_END_OF_BUFFER 130
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[330] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      130,  129,  128,  127,   97,   43,   78,  119,   56,  111,
      112,   77,   75,  116,   76,  118,   82,  120,  120,  117,
      115,   91,   94,   92,  125,  109,  110,   95,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  113,  103,  114,  106,
       44,   55,   54,   68,   69,   70,   73,   74,   58,   66,
      129,  124,  124,    0,   93,   79,   99,  100,   80,   85,
       83,   84,  108,  122,   67,   72,   86,    0,  120,  126,
      122,  126,  120,  126,  126,  104,   87,   96,   90,  105,

      125,  124,  125,  124,  101,  124,  124,  124,  124,    7,
      124,  124,  124,  124,  124,   15,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  102,   98,   44,   45,   51,
       52,   46,   47,   48,   50,   49,    0,   68,   71,   58,
       64,   65,   59,   60,   61,   63,   62,    0,   81,    0,
      122,    0,  122,  126,  124,  126,  124,  124,  124,  123,
      124,  122,  121,  121,  120,  126,   88,   89,  107,  124,
      124,  124,  124,    6,  124,  124,  124,  124,   11,  124,
      124,  124,   20,  124,  124,  124,  124,  124,  124,  124,

      124,  124,  124,  124,  124,  124,   37,  124,    2,   39,
      124,  124,  124,   45,    0,    0,    0,  123,  122,    0,
      123,  123,  126,  121,  126,  121,  124,    0,  122,  126,
      120,  124,    3,  124,  124,    8,  124,  124,  124,  124,
      124,  124,   18,  124,   21,  124,  124,  124,  124,  124,
      124,  124,  124,  124,   33,  124,  124,   36,   38,  124,
       41,  124,    0,    0,  123,  123,    0,  122,  124,    4,
        5,  124,   10,   12,  124,  124,  124,   19,  124,  124,
      124,   27,  124,  124,  124,  124,   32,   34,   35,   40,
       42,    0,    0,  122,    0,  124,  124,  124,  124,  124,

       17,   22,  124,  124,   29,  124,  124,  124,   30,   31,
       53,    0,  124,    9,   13,   14,  124,  124,   24,   28,
       25,  124,   57,    1,   16,   23,  124,   26,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   26,   27,   26,
       28,   28,   28,   28,   28,   29,   28,   28,   28,   28,
       28,   28,   30,   28,   28,   28,   28,   31,   28,   28,
       32,   33,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   28,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    3,    1,
        1,    4,    1,    1,    1,    1,    4,    5,    5,    1,
        1,    1,    1,    1,    6,    6,    6,    7,    7,    7,
        7,    1,    8,    1,    1,    7,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[348] =
    {   0,
        0,    0,   60,   61,   56,   57,  889,  888,   62,   63,
      890,   71,   72,  893,   74,   73,   75,   76,   77,   85,
       86,  112,  113,  114,  115,  127,  143,  179,   61,  123,
      125,  241,  242,  243,  279,  128,  129,  341,    0,  851,
       86,   89,   78,  125,  125,  851,  850,   29,  211,  116,
      845,  127,  209,  848,   38,  839,  342,  343,  344,  345,
        0,  893,  349,    0,  866,  893,  893,  893,    0,  893,
      359,  347,  893,  355,  357,  359,  365,  371,  394,  392,
      404,  406,  407,  419,  415,  416,  418,  445,  217,  481,
      232,  237,  531,  556,  239,  430,  421,  548,  549,  563,

        0,    0,    0,    0,  572,  828,   32,  844,  838,    0,
      825,  823,  829,  826,  822,    0,  822,  812,  817,  813,
      822,  823,  827,  828,  126,  811,  828,  812,  309,  402,
      811,  125,  817,  806,  819,  575,  576,    0,  465,  893,
      893,  893,  893,  893,  893,  893,    0,    0,  893,    0,
      893,  893,  893,  893,  893,  893,  893,    0,  584,  457,
      233,  530,  588,    0,    0,    0,    0,  541,  614,  616,
      618,  326,  641,  666,  693,  532,  587,  615,  617,  804,
      817,  818,  802,    0,  814,  813,  776,  786,  784,   40,
      746,  729,    0,  718,  724,  710,  715,  204,  706,  703,

      708,  712,  697,  692,  697,  698,    0,  683,    0,    0,
      675,  677,  668,  475,    0,    0,  338,  712,  622,  591,
        0,  395,  653,    0,  684,    0,  681,  371,  386,  681,
      696,  648,    0,  654,  643,    0,  640,  647,  639,  635,
      631,  622,    0,  630,    0,  634,  616,  628,  606,  620,
      614,  586,  597,  578,    0,  568,  570,    0,    0,  562,
        0,  562,    0,    0,  893,  718,  709,  728,  563,    0,
        0,  550,    0,  541,  521,  530,  510,    0,  509,  518,
      519,  384,  506,  516,  430,  433,    0,    0,    0,    0,
        0,    0,    0,  699,  731,  432,  411,  401,  415,  396,

        0,    0,  389,  377,    0,  366,  362,  330,    0,    0,
      893,  351,  295,    0,    0,    0,  196,  134,    0,    0,
        0,   87,  893,    0,    0,    0,   85,    0,  893,  769,
      777,  785,  793,  801,  805,  812,  819,  827,  830,  833,
      835,  837,  839,  841,  843,  845,  847
    } ;

static const flex_int16_t yy_def[348] =
    {   0,
      329,    1,  330,  330,  331,  331,  332,  332,  333,  333,
      329,  334,  334,  329,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  329,   28,  334,
      334,  334,  334,  334,  329,  334,  334,  334,  335,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,  334,  334,  334,  334,
      336,  329,  329,  337,  329,  329,  329,  329,  338,  329,
      329,  334,  329,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  329,  334,  334,  334,  334,   28,  329,
       90,   90,   90,   90,  339,  334,  334,  334,  334,  334,

      335,   35,   35,  335,  334,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,  334,  334,  336,  329,  329,
      329,  329,  329,  329,  329,  329,  340,  337,  329,  338,
      329,  329,  329,  329,  329,  329,  329,  341,  334,  329,
      329,  329,  329,  339,   90,   90,  339,   90,  334,  339,
      334,   90,  339,   90,  339,  339,  334,  334,  334,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,  329,  342,  343,  329,  329,  329,  329,
      339,  170,  339,  339,  173,   90,  173,  329,  339,  339,
      175,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,  344,  345,  329,  329,  329,  329,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,  346,  347,  329,  329,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
      329,  329,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,  329,   35,   35,   35,   35,   35,    0,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329
    } ;

static const flex_int16_t yy_nxt[959] =
    {   0,
       12,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   35,   35,   35,   35,   35,
       35,   36,   12,   37,   38,   39,   40,   35,   41,   42,
       43,   44,   35,   35,   45,   35,   35,   46,   47,   48,
       49,   50,   51,   52,   53,   35,   54,   55,   35,   56,
       35,   57,   58,   59,   60,   62,   62,   65,   65,  120,
       70,   70,   66,   66,   73,   73,   73,   73,   73,   73,
       73,  133,  134,   77,  121,  181,  182,  241,   73,   73,
      242,   90,   63,   63,   71,   71,   75,   76,   78,   74,

       74,   74,   74,   74,   74,   74,   73,   73,   73,   73,
       73,   73,   73,   74,   74,   73,   73,   73,   73,   90,
       73,   73,  107,   79,  328,  111,   73,  327,   73,  109,
       73,   73,   73,  108,   80,   81,  112,   82,   83,  110,
       74,   74,   74,   74,   84,   84,   73,   73,   73,   73,
       73,   74,  124,   74,   85,   74,   74,   74,   73,   86,
       73,  113,   73,   73,   73,   87,  116,  127,  125,  114,
      198,   74,  209,  117,  326,  115,  199,  210,   73,   74,
       74,   74,  128,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   88,   74,   89,   89,   74,   74,

       74,   74,   74,   90,   91,   92,   90,   93,   90,   94,
       74,   74,   74,   74,   95,   90,   90,   90,   91,   92,
       91,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   94,   90,   90,
       74,   74,   74,   74,   73,   73,   73,   90,  122,  169,
      325,  169,  129,  249,  170,  170,  175,  175,  168,  160,
      250,  130,   96,   97,   98,   99,  100,  123,  131,   74,
       74,   74,  168,  160,  176,   90,   73,   73,   73,   72,
       72,   72,   73,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,  101,  101,   72,   72,

       72,   72,   72,  102,  102,  102,  102,  103,  102,  102,
       72,   72,   72,   72,  104,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
       72,   72,   72,   72,   73,   73,   73,   73,   73,  324,
       73,  139,  168,  203,  140,  218,  218,  141,   73,  323,
       73,  204,   73,  105,  151,  136,  168,  152,   73,   74,
       74,   74,   74,   74,   73,   74,   73,   73,   73,   73,
       73,  142,   73,   74,  322,   74,  143,   74,  163,  163,
       73,  153,   73,   74,   73,   73,  154,   73,  144,   74,

       73,  145,  321,  146,  147,  137,   73,   73,  155,   73,
       73,  156,  230,  157,  158,  320,  159,  319,   73,   73,
       74,   73,   74,  164,   73,  305,  230,   73,  318,   73,
      164,  306,   74,   73,   74,   74,   84,   84,  205,   73,
      317,   73,   73,   74,   74,  160,   74,  161,   73,   74,
       73,   73,  177,   73,  162,  316,   73,  206,   74,  160,
      315,  207,  163,  163,  314,   73,  214,  214,  214,  217,
      313,  217,  310,   74,  218,  218,  214,  214,  214,  309,
       73,   72,   72,   72,   73,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,  164,  164,

       72,   72,   72,   72,   72,  165,  165,  165,  165,  166,
      165,  165,   72,   72,   72,   72,  167,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,   72,   72,   72,   72,  171,   84,   84,  175,
      175,   73,   73,  169,  308,  169,  172,  168,  170,  170,
      307,  304,  303,  302,  301,  162,   73,  176,  300,  299,
      172,  168,  172,  173,  173,   73,   74,   74,   73,   73,
      174,  174,  174,   73,   73,  178,  179,   73,  298,  297,
       73,   74,  174,  174,  174,  174,  174,  174,   73,  296,

       74,  291,  290,   74,   74,  163,  163,   73,  163,  163,
       73,   73,   74,  161,  160,   74,  219,   73,   73,   73,
       73,   73,   73,  220,  289,  288,  220,  161,  160,  161,
      287,  218,  218,  170,  170,  163,  163,  286,  285,  268,
      268,  221,   74,   74,  222,   74,   74,  161,  160,   73,
       73,  223,   73,   73,  284,  221,  283,  221,  173,  173,
      282,  161,  160,  161,  281,  173,  173,  173,  280,  224,
      170,  170,  279,  278,  277,  276,  225,  173,  173,  173,
      173,  173,  173,  173,  173,  275,  274,  273,  223,  272,
      174,  174,  174,  217,  226,  217,  271,  270,  170,  170,

      269,  227,  174,  174,  174,  174,  174,  174,  228,  164,
      175,  175,  164,  164,  164,  262,  268,  268,  229,  230,
      261,  231,  260,  259,  164,  160,  218,  218,  176,  218,
      218,  164,  229,  230,  229,  218,  218,  265,  258,  160,
      266,  257,  256,  265,  267,  268,  268,  267,  268,  268,
      255,  265,  254,  265,  160,  253,  294,  265,  252,  265,
      251,  248,  247,  295,  246,  245,  295,  244,  160,   61,
       61,   61,   61,   61,   61,   61,   61,   64,   64,   64,
       64,   64,   64,   64,   64,   67,   67,   67,   67,   67,
       67,   67,   67,   69,   69,   69,   69,   69,   69,   69,

       69,   72,   72,   72,   72,  243,   72,   72,   72,  101,
      101,  101,  138,  240,  138,  138,  138,  138,  138,  148,
      148,  148,  239,  148,  148,  148,  148,  150,  150,  238,
      150,  150,  150,  150,  164,  164,  164,  215,  215,  216,
      216,  263,  263,  264,  264,  292,  292,  293,  293,  311,
      311,  312,  312,  237,  236,  235,  234,  233,  232,  213,
      212,  211,  208,  202,  201,  200,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  180,  149,  135,  132,  126,  119,  118,  106,  329,
       68,   68,   11,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329
    } ;

static const flex_int16_t yy_chk[959] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    6,   48,
        9,   10,    5,    6,   12,   13,   16,   15,   17,   18,
       19,   55,   55,   18,   48,  107,  107,  190,   20,   21,
      190,   29,    3,    4,    9,   10,   15,   17,   18,   12,

       13,   16,   15,   17,   18,   19,   12,   13,   16,   15,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   29,
       20,   21,   41,   22,  327,   43,   30,  322,   31,   42,
       26,   36,   37,   41,   22,   23,   43,   25,   25,   42,
       22,   23,   24,   25,   26,   26,   27,   22,   23,   24,
       25,   30,   50,   31,   27,   26,   36,   37,   30,   27,
       31,   44,   26,   36,   37,   27,   45,   52,   50,   44,
      125,   27,  132,   45,  318,   44,  125,  132,   27,   28,
       28,   28,   52,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,

       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   32,   33,   34,   89,   49,   92,
      317,   92,   53,  198,   92,   92,   95,   95,   91,  161,
      198,   53,   32,   32,   33,   34,   34,   49,   53,   32,
       33,   34,   91,  161,   95,   89,   32,   33,   34,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   38,   57,   58,   59,   60,  313,
       72,   63,  172,  129,   63,  217,  217,   63,   74,  312,
       75,  129,   76,   38,   71,   58,  172,   71,   77,   38,
       57,   58,   59,   60,   78,   72,   38,   57,   58,   59,
       60,   63,   72,   74,  308,   75,   63,   76,  228,  228,
       74,   71,   75,   77,   76,   80,   71,   79,   63,   78,

       77,   63,  307,   63,   63,   58,   78,   81,   71,   82,
       83,   71,  229,   71,   71,  306,   79,  304,   85,   86,
       80,   87,   79,  222,   97,  282,  229,   80,  303,   79,
      222,  282,   81,   96,   82,   83,   84,   84,  130,   81,
      300,   82,   83,   85,   86,   84,   87,   84,   88,   97,
       85,   86,   96,   87,   84,  299,   97,  130,   96,   84,
      298,  130,   88,   88,  297,   96,  139,  139,  139,  160,
      296,  160,  286,   88,  160,  160,  214,  214,  214,  285,
       88,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,

       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   93,  162,  162,  176,
      176,   98,   99,  168,  284,  168,   93,   93,  168,  168,
      283,  281,  280,  279,  277,  162,  100,  176,  276,  275,
       93,   93,   93,   94,   94,  105,   98,   99,  136,  137,
       94,   94,   94,   98,   99,  100,  100,  159,  274,  272,
      177,  100,   94,   94,   94,   94,   94,   94,  100,  269,

      105,  262,  260,  136,  137,  163,  163,  105,  220,  220,
      136,  137,  159,  163,  163,  177,  163,  169,  178,  159,
      179,  171,  177,  163,  257,  256,  220,  163,  163,  163,
      254,  169,  169,  170,  170,  171,  171,  253,  252,  219,
      219,  170,  169,  178,  170,  179,  171,  219,  219,  169,
      178,  170,  179,  171,  251,  170,  250,  170,  173,  173,
      249,  219,  219,  219,  248,  173,  173,  173,  247,  173,
      223,  223,  246,  244,  242,  241,  173,  173,  173,  173,
      173,  173,  173,  174,  174,  240,  239,  238,  223,  237,
      174,  174,  174,  230,  174,  230,  235,  234,  230,  230,

      232,  174,  174,  174,  174,  174,  174,  174,  175,  227,
      175,  175,  225,  231,  231,  213,  294,  294,  175,  175,
      212,  175,  211,  208,  231,  294,  267,  267,  175,  218,
      218,  231,  175,  175,  175,  266,  266,  218,  206,  294,
      218,  205,  204,  266,  267,  268,  268,  218,  295,  295,
      203,  218,  202,  218,  268,  201,  268,  266,  200,  266,
      199,  197,  196,  268,  195,  194,  295,  192,  268,  330,
      330,  330,  330,  330,  330,  330,  330,  331,  331,  331,
      331,  331,  331,  331,  331,  332,  332,  332,  332,  332,
      332,  332,  332,  333,  333,  333,  333,  333,  333,  333,

      333,  334,  334,  334,  334,  191,  334,  334,  334,  335,
      335,  335,  336,  189,  336,  336,  336,  336,  336,  337,
      337,  337,  188,  337,  337,  337,  337,  338,  338,  187,
      338,  338,  338,  338,  339,  339,  339,  340,  340,  341,
      341,  342,  342,  343,  343,  344,  344,  345,  345,  346,
      346,  347,  347,  186,  185,  183,  182,  181,  180,  135,
      134,  133,  131,  128,  127,  126,  124,  123,  122,  121,
      120,  119,  118,  117,  115,  114,  113,  112,  111,  109,
      108,  106,   65,   56,   54,   51,   47,   46,   40,   11,
        8,    7,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[130] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 1, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "sample.l"




#line 22 "sample.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include "ParseNumbers.h"
#pragma warning(disable : 4996)
#line 759 "sample.flex.cpp"
#line 760 "sample.flex.cpp"

#define INITIAL 0
#define CONST_STRING 1
#define MULTILINE_COMMENT 2
#define ONELINE_COMMENT 3
#define CHAR 4

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 30 "sample.l"



#line 34 "sample.l"
int64_t int_number;
double real_number;
int int_buffer;
char buffer[1000];
char buf_char[2];


#line 905 "sample.flex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 330 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 329 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "sample.l"
{ printf("(%s) - Found KW_ABSTRACT\n", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "sample.l"
{ printf("(%s) - Found KW_VAL\n", yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "sample.l"
{ printf("(%s) - Found KW_CASE\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "sample.l"
{ printf("(%s) - Found KW_CATCH\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "sample.l"
{ printf("(%s) - Found KW_CLASS\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "sample.l"
{ printf("(%s) - Found KW_DEF\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 47 "sample.l"
{ printf("(%s) - Found KW_do\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 48 "sample.l"
{ printf("(%s) - Found KW_ELSE\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "sample.l"
{ printf("(%s) - Found KW_EXTENDS\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "sample.l"
{ printf("(%s) - Found KW_FALSE\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "sample.l"
{ printf("(%s) - Found KW_FOR\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "sample.l"
{ printf("(%s) - Found KW_FINAL\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "sample.l"
{ printf("(%s) - Found KW_FINALLY\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "sample.l"
{ printf("(%s) - Found KW_forSome\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "sample.l"
{ printf("(%s) - Found KW_IF\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "sample.l"
{ printf("(%s) - Found KW_IMPLICIT\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "sample.l"
{ printf("(%s) - Found KW_IMPORT\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "sample.l"
{ printf("(%s) - Found KW_LAZY\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "sample.l"
{ printf("(%s) - Found KW_MATCH\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "sample.l"
{ printf("(%s) - Found KW_NEW\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "sample.l"
{ printf("(%s) - Found KW_NULL\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "sample.l"
{ printf("(%s) - Found KW_OBJECT\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "sample.l"
{ printf("(%s) - Found KW_OVERRIDE\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "sample.l"
{ printf("(%s) - Found KW_PACKAGE\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "sample.l"
{ printf("(%s) - Found KW_PRIVATE\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "sample.l"
{ printf("(%s) - Found KW_PROTECTED\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "sample.l"
{ printf("(%s) - Found KW_PRINT\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "sample.l"
{ printf("(%s) - Found KW_PRINTLN\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "sample.l"
{ printf("(%s) - Found KW_PRINTF\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "sample.l"
{ printf("(%s) - Found KW_RETURN\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "sample.l"
{ printf("(%s) - Found KW_SEALED\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "sample.l"
{ printf("(%s) - Found KW_SUPER\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "sample.l"
{ printf("(%s) - Found KW_THIS\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "sample.l"
{ printf("(%s) - Found KW_THROW\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "sample.l"
{ printf("(%s) - Found KW_TRAIT\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "sample.l"
{ printf("(%s) - Found KW_TRUE\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "sample.l"
{ printf("(%s) - Found KW_TRY\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "sample.l"
{ printf("(%s) - Found KW_TYPE\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "sample.l"
{ printf("(%s) - Found KW_VAR\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "sample.l"
{ printf("(%s) - Found KW_WHILE\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "sample.l"
{ printf("(%s) - Found KW_WITH\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "sample.l"
{ printf("(%s) - Found KW_YIELD\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "sample.l"
{buffer[0]=0; BEGIN(CONST_STRING);}
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 86 "sample.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 87 "sample.l"

	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "sample.l"
{strcat(buffer, "\\");}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "sample.l"
{strcat(buffer, "\b");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "sample.l"
{strcat(buffer, "\n");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "sample.l"
{strcat(buffer, "\t");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "sample.l"
{strcat(buffer, "\r");}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "sample.l"
{strcat(buffer, "\"");}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "sample.l"
{strcat(buffer, "\'");}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "sample.l"
{ 
    unsigned int unicode_value = strtol(yytext + 2, NULL, 16); // Преобразуем шестнадцатеричное значение в целое число
    if (unicode_value >= 0 && unicode_value <= 255) { // Проверяем диапазон
        buf_char[0] = (wchar_t)unicode_value; // Присваиваем его буферу
        buf_char[1] = 0; // Завершаем строку
        strcat(buffer, buf_char); // Конкатенируем в буфер
    } else {
        printf("Error: Unicode value is out of range (0000-0255)\n");
    }
}
	YY_BREAK
case YY_STATE_EOF(CONST_STRING):
#line 105 "sample.l"
{printf("(%s) - Found ERROR_STRING\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 106 "sample.l"
{printf("(%s) - Found NOT_ESCAPED_SLASH\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 107 "sample.l"
{printf("(%s) - Found CONST_STRING\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "sample.l"
{buffer[0]=0; BEGIN(CHAR);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "sample.l"
{
    yytext[strlen(yytext)-1] = '\0'; // Удаляем одинарную кавычку в конце
    wchar_t buf_char[1]; // Буфер для хранения символа Unicode
    unsigned int unicode_value = strtol(yytext + 2, NULL, 16); // Преобразуем шестнадцатеричное значение в целое число

    // Проверяем, находится ли значение в диапазоне от 0 до 255
    if (unicode_value >= 0 && unicode_value <= 255) {
        buf_char[0] = (wchar_t)unicode_value; // Присваиваем его буферу
        printf("(%lc) - Found CHAR\n", buf_char[0]); // Выводим символ
    } else {
        printf("Error: Unicode value is out of range (0000-0255)\n");
    }

    BEGIN(INITIAL);
}
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 125 "sample.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 126 "sample.l"
{strcat(buffer, "\\");}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "sample.l"
{strcat(buffer, "\b");}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "sample.l"
{strcat(buffer, "\n");}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 129 "sample.l"
{strcat(buffer, "\t");}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 130 "sample.l"
{strcat(buffer, "\r");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "sample.l"
{strcat(buffer, "\"");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 132 "sample.l"
{strcat(buffer, "\'");}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 133 "sample.l"
{printf("(%s) - Error CHAR\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 134 "sample.l"
{
if(strlen(buffer)==1){
printf("(%s) - Found CHAR\n", buffer); BEGIN(INITIAL);
}else{
printf("(%s) - Error CHAR\n", buffer); BEGIN(INITIAL);
}
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 142 "sample.l"
{buffer[0]=0; BEGIN(MULTILINE_COMMENT);}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 143 "sample.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 144 "sample.l"
{strcat(buffer, "*");}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 145 "sample.l"
{strcat(buffer, "/");}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 146 "sample.l"
{ printf("(%s) - Error MULTILINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 147 "sample.l"
{printf("(%s) - Found MULTILINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 149 "sample.l"
{buffer[0]=0; BEGIN(ONELINE_COMMENT);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 150 "sample.l"
{strcat(buffer, yytext);}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 151 "sample.l"
{printf("(%s) - Found ONELINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(ONELINE_COMMENT):
#line 152 "sample.l"
{printf("(%s) - Found ONELINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 155 "sample.l"
{ printf("(%s) - Found PLUS_OPERATOR\n", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 156 "sample.l"
{ printf("(%s) - Found MINUS_OPERATOR\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 157 "sample.l"
{ printf("(%s) - Found MUL_OPERATOR\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 158 "sample.l"
{ printf("(%s) - Found MOD_OPERATOR\n", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 159 "sample.l"
{ printf("(%s) - Found MOD_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 160 "sample.l"
{ printf("(%s) - Found EXP_OPERATOR\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 161 "sample.l"
{ printf("(%s) - Found EXP_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 162 "sample.l"
{ printf("(%s) - Found DIV_OPERATOR\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 163 "sample.l"
{ printf("(%s) - Found PLUS_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 164 "sample.l"
{ printf("(%s) - Found MINUS_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 165 "sample.l"
{ printf("(%s) - Found MUL_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 166 "sample.l"
{ printf("(%s) - Found DIV_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 167 "sample.l"
{ printf("(%s) - Found LESS_OR_EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 168 "sample.l"
{ printf("(%s) - Found LEFTSHIFT_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 169 "sample.l"
{ printf("(%s) - Found RIGHTSHIFT_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 170 "sample.l"
{ printf("(%s) - Found MORE_OR_EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 171 "sample.l"
{ printf("(%s) - Found LESS_OPERATOR\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 172 "sample.l"
{ printf("(%s) - Found MORE_OPERATOR\n", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 173 "sample.l"
{ printf("(%s) - Found NOT_EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 174 "sample.l"
{ printf("(%s) - Found ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 175 "sample.l"
{ printf("(%s) - Found CIRCUMFLEX\n", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 178 "sample.l"
{ printf("(%s) - Found EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 179 "sample.l"
{ printf("(%s) - Found NOT_OPERATOR\n", yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 180 "sample.l"
{ printf("(%s) - Found OR_OPERATOR\n", yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 181 "sample.l"
{ printf("(%s) - Found AND_OPERATOR\n", yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 183 "sample.l"
{ printf("(%s) - Found BITWISE_AND_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 184 "sample.l"
{ printf("(%s) - Found BITWISE_EX_OR_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 185 "sample.l"
{ printf("(%s) - Found BITWISE_IN_OR_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 186 "sample.l"
{ printf("(%s) - Found BITWISE_OR_OPERATOR\n", yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 187 "sample.l"
{ printf("(%s) - Found BITWISE_LEFTSHIFT_OPERATOR\n", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 188 "sample.l"
{ printf("(%s) - Found BITWISE_RIGHTSHIFT_OPERATOR\n", yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 189 "sample.l"
{ printf("(%s) - Found BITWISE_onesCOMPLEMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 190 "sample.l"
{ printf("(%s) - Found BITWISE_RIGHTSHIF_ZERO_OPERATOR\n", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 192 "sample.l"
{ printf("(%s) - Found TUPLE\n", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 194 "sample.l"
{ printf("(%s) - Found SQUARE_BRACKET\n", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 195 "sample.l"
{ printf("(%s) - Found SQUARE_BRACKET\n", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 196 "sample.l"
{ printf("(%s) - Found ROUND_BRACKET\n", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 197 "sample.l"
{ printf("(%s) - Found ROUND_BRACKET\n", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 198 "sample.l"
{ printf("(%s) - Found BRACE\n", yytext); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 199 "sample.l"
{ printf("(%s) - Found BRACE\n", yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 200 "sample.l"
{ printf("(%s) - Found SEMICOLON\n", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 201 "sample.l"
{ printf("(%s) - Found COMMA\n", yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 202 "sample.l"
{ printf("(%s) - Found COLON\n", yytext); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 203 "sample.l"
{ printf("(%s) - Found DOT\n", yytext); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 204 "sample.l"
{ printf("(%s) - Found AMPERSAND\n", yytext); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 209 "sample.l"
{
    parse_integer(&int_number, yytext, 10);
    printf("Line %d: found decimal number: %d\n", yylineno, int_number);
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 214 "sample.l"
{
    parse_integer(&int_number, yytext, 16);
    printf("Line %d: found hex number: %d\n", yylineno, int_number);
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 220 "sample.l"
{
    parse_real(&real_number, yytext);
    printf("Line %d: found real number: %f\n", yylineno, real_number);
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 225 "sample.l"
{
    parse_real(&real_number, yytext);
    printf("Line %d: found real exponent number: %f\n", yylineno, real_number);
}
	YY_BREAK
case 124:
/* rule 124 can match eol */
YY_RULE_SETUP
#line 231 "sample.l"
{
    printf("Error: Invalid integer format at line %d: '%s'\n", yylineno, yytext);
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 235 "sample.l"
{ printf("(%s) - Found IDENTIFIER\n", yytext); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 238 "sample.l"
{ printf("(%s) - Error IDENTIFIER\n", yytext); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 240 "sample.l"
{}
	YY_BREAK
case 128:
/* rule 128 can match eol */
YY_RULE_SETUP
#line 241 "sample.l"
{}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 243 "sample.l"
ECHO;
	YY_BREAK
#line 1679 "sample.flex.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 330 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 330 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 329);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 243 "sample.l"




