#line 1 "sample.flex.cpp"

#line 3 "sample.flex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext

#include "FlexLexer.h"

inline int yyFlexLexer::yywrap() { return 1; }

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 131
#define YY_END_OF_BUFFER 132
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[315] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      132,  130,  128,  129,   99,   43,   80,  121,   57,  113,
      114,   79,   77,  118,   78,  120,   84,  122,  122,  119,
      117,   93,   96,   94,  126,  111,  112,   97,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  115,  105,  116,  108,   44,
       54,   56,   55,   70,   71,   72,   75,   76,   59,   67,
       68,  131,  128,   95,   81,  101,  102,   82,   87,   85,
       86,  110,  124,   69,   74,   88,    0,  122,  127,  124,
      127,  122,  127,  127,  106,   89,   98,   92,  107,  126,

      103,  126,  126,  126,  126,    7,  126,  126,  126,  126,
      126,   15,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  104,  100,   44,   45,   51,   52,   46,   47,   48,
       50,   49,    0,   70,   73,   59,   65,   66,   60,   61,
       62,   64,   63,    0,   83,    0,  124,    0,  124,  127,
      127,    0,  125,  124,  123,  122,  127,   90,   91,  109,
      126,  126,  126,  126,    6,  126,  126,  126,  126,   11,
      126,  126,  126,   20,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,   37,  126,    2,

       39,  126,  126,  126,   45,    0,    0,  125,  124,    0,
      125,  125,  127,  123,  127,  122,  126,    3,  126,  126,
        8,  126,  126,  126,  126,  126,  126,   18,  126,   21,
      126,  126,  126,  126,  126,  126,  126,  126,  126,   33,
      126,  126,   36,   38,  126,   41,  126,    0,    0,  125,
      125,    0,  124,  126,    4,    5,  126,   10,   12,  126,
      126,  126,   19,  126,  126,  126,   27,  126,  126,  126,
      126,   32,   34,   35,   40,   42,    0,    0,  124,    0,
      126,  126,  126,  126,  126,   17,   22,  126,  126,   29,
      126,  126,  126,   30,   31,   53,    0,  126,    9,   13,

       14,  126,  126,   24,   28,   25,  126,   58,    1,   16,
       23,  126,   26,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   26,   27,   26,
       28,   28,   28,   28,   28,   29,   28,   28,   28,   28,
       28,   28,   30,   28,   28,   28,   28,   31,   28,   28,
       32,   33,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   28,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    4,    1,
        1,    5,    1,    1,    1,    6,    5,    7,    7,    1,
        1,    1,    1,    1,    7,    7,    7,    8,    8,    8,
        8,    1,    2,    1,    1,    8,    7,    7,    7,    7,
        7,    7,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[333] =
    {   0,
        0,    0,   63,   64,   56,   59,  500,  499,   69,   71,
      501,  504,  498,  504,  476,  504,  475,   67,  504,  504,
      504,   65,  474,  504,   58,   65,   75,   89,  133,  504,
      504,   63,  473,   70,    0,  504,  504,  472,  456,   52,
       50,   47,   66,   70,  456,  455,   58,   71,   73,  450,
       80,   79,  453,   89,  444,  504,   90,  504,  504,    0,
      504,  504,  132,    0,  471,  504,  504,  504,    0,  504,
      504,  148,  485,  504,  504,  504,  504,  463,  504,  504,
      504,  504,  173,  504,  504,  504,  124,    0,    0,  117,
      148,  179,  204,  128,  462,  504,  504,  504,  132,    0,

      504,  430,  117,  446,  440,    0,  427,  425,  431,  428,
      424,    0,  424,  414,  419,  415,  424,  425,  429,  430,
      132,  413,  430,  414,   92,  152,  413,   74,  419,  408,
      421,  504,  504,    0,  176,  504,  504,  504,  504,  504,
      504,  504,    0,    0,  504,    0,  504,  504,  504,  504,
      504,  504,  504,    0,  504,  198,  149,  214,  229,    0,
      221,  175,  248,  169,  189,  275,  242,  504,  504,  504,
      406,  419,  420,  404,    0,  416,  415,  401,  417,  423,
      176,  392,  412,    0,  402,  408,  395,  400,  178,  391,
      389,  396,  402,  388,  390,  395,  398,    0,  397,    0,

        0,  389,  392,  387,  249,    0,    0,  263,  294,  244,
        0,  228,  278,    0,  398,  289,  380,    0,  388,  377,
        0,  380,  388,  380,  376,  381,  372,    0,  380,    0,
      384,  369,  384,  365,  376,  370,  353,  355,  342,    0,
      297,  298,    0,    0,  311,    0,  310,    0,    0,  504,
      304,  291,  313,  311,    0,    0,  307,    0,  297,  294,
      302,  278,    0,  271,  279,  276,  231,  251,  261,  248,
      255,    0,    0,    0,    0,    0,    0,    0,  310,  320,
      248,  232,  225,  242,  231,    0,    0,  235,  231,    0,
      218,  218,  199,    0,    0,  504,  240,  183,    0,    0,

        0,  182,  185,    0,    0,    0,  174,  504,    0,    0,
        0,  167,    0,  504,  356,  364,  372,  380,  383,  385,
      393,  401,  409,  411,  192,  190,  177,  161,  143,  133,
      117,   72
    } ;

static const flex_int16_t yy_def[333] =
    {   0,
      314,    1,  315,  315,  316,  316,  317,  317,  318,  318,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  319,  319,  314,
      314,  314,  314,  314,  320,  314,  314,  314,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  314,  314,  314,  314,  321,
      314,  314,  314,  322,  314,  314,  314,  314,  323,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,   29,  324,  324,
      324,  324,  324,  324,  314,  314,  314,  314,  314,  320,

      314,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  314,  314,  321,  314,  314,  314,  314,  314,  314,
      314,  314,  325,  322,  314,  323,  314,  314,  314,  314,
      314,  314,  314,  326,  314,  314,  314,  314,  314,  324,
      324,  314,  324,  324,   93,  324,  324,  314,  314,  314,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  314,  327,  328,  314,  314,  314,
      324,  163,  324,  324,   93,  166,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  329,  330,  314,
      314,  314,  314,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  331,  332,  314,  314,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  314,  314,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  314,  320,  320,
      320,  320,  320,    0,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314
    } ;

static const flex_int16_t yy_nxt[570] =
    {   0,
       12,   13,   14,   12,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   35,   35,   35,   35,   35,
       35,   36,   12,   37,   38,   35,   39,   35,   40,   41,
       42,   43,   35,   35,   44,   35,   35,   45,   46,   47,
       48,   49,   50,   51,   52,   35,   53,   54,   35,   55,
       35,   56,   57,   58,   59,   61,   61,   65,   62,   62,
       65,   70,   66,   70,   76,   66,   78,   71,  297,   71,
       81,   82,   83,   83,   95,   96,   84,   79,  103,   77,
      105,   85,   98,   99,  107,   63,   63,   86,  116,  104,

      106,   72,  109,   72,   87,  108,   88,   88,  118,  120,
      110,  112,  132,  117,   90,   91,  111,   92,  113,   93,
      123,  200,  125,  296,   94,  121,  201,  119,   90,   91,
       90,  126,  129,  130,  135,  124,  194,  136,  127,  278,
      137,  159,  159,  161,  195,  166,  166,   93,   87,  277,
       88,   88,  133,  147,  169,  170,  148,  161,   90,   91,
      162,   92,  162,  167,  138,  163,  163,  249,   94,  139,
      172,  173,   90,   91,   90,  156,  189,  205,  205,  205,
      149,  140,  190,  248,  141,  150,  142,  143,  196,  156,
       83,   83,  208,  208,   87,  161,  207,  151,  206,  156,

      152,  157,  153,  154,  164,  161,  313,  197,  158,  161,
      162,  198,  162,  156,  312,  208,  208,  214,  164,  161,
      164,  165,  165,  226,  215,  311,  227,  234,  165,  165,
      165,   83,   83,  162,  235,  162,  310,  309,  163,  163,
      165,  165,  165,  165,  165,  165,  159,  159,  308,  158,
      205,  205,  205,  307,  157,  156,  160,  209,  306,  166,
      166,  159,  159,  160,  210,  163,  163,  305,  157,  156,
      157,  304,  290,  211,  303,  302,  212,  167,  291,  210,
      208,  208,  301,  213,  300,  299,  298,  211,  250,  211,
       87,  251,  166,  166,  295,  163,  163,  294,  252,  293,

      164,  161,  250,  216,  250,  292,  160,  160,  208,  208,
      167,  253,  253,  213,  164,  161,  164,  160,  289,  157,
      156,  208,  208,  288,  160,  287,  252,  253,  253,  250,
      253,  253,  286,  157,  156,  157,  156,  253,  253,  156,
      285,  279,  284,  250,  283,  250,  282,  281,  280,  276,
      156,  275,  274,  156,  273,  280,   60,   60,   60,   60,
       60,   60,   60,   60,   64,   64,   64,   64,   64,   64,
       64,   64,   67,   67,   67,   67,   67,   67,   67,   67,
       69,   69,   69,   69,   69,   69,   69,   69,   89,   89,
       89,  100,  100,  134,  272,  271,  134,  134,  134,  134,

      134,  144,  144,  144,  144,  270,  144,  144,  144,  146,
      269,  146,  268,  146,  146,  146,  146,  160,  160,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  215,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  233,  232,  231,  230,
      229,  228,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  204,  203,  202,  199,  193,  192,  191,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  171,  168,  155,   73,  145,  131,  128,
      122,  115,  114,  102,  101,   97,   80,   75,   74,   73,

      314,   68,   68,   11,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314
    } ;

static const flex_int16_t yy_chk[570] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    3,    4,
        6,    9,    5,   10,   18,    6,   22,    9,  332,   10,
       25,   25,   26,   26,   32,   32,   27,   22,   40,   18,
       41,   27,   34,   34,   42,    3,    4,   27,   47,   40,

       41,    9,   43,   10,   28,   42,   28,   28,   48,   49,
       43,   44,   57,   47,   28,   28,   43,   28,   44,   28,
       51,  128,   52,  331,   28,   49,  128,   48,   28,   28,
       28,   52,   54,   54,   63,   51,  125,   63,   52,  330,
       63,   87,   87,   90,  125,   94,   94,   28,   29,  329,
       29,   29,   57,   72,   99,   99,   72,   90,   29,   29,
       91,   29,   91,   94,   63,   91,   91,  328,   29,   63,
      103,  103,   29,   29,   29,  157,  121,  135,  135,  135,
       72,   63,  121,  327,   63,   72,   63,   63,  126,  157,
       83,   83,  162,  162,   92,  164,  326,   72,  325,   83,

       72,   83,   72,   72,   92,   92,  312,  126,   83,  164,
      156,  126,  156,   83,  307,  156,  156,  165,   92,   92,
       92,   93,   93,  181,  165,  303,  181,  189,   93,   93,
       93,  158,  158,  161,  189,  161,  302,  298,  161,  161,
       93,   93,   93,   93,   93,   93,  159,  159,  297,  158,
      205,  205,  205,  293,  159,  159,  212,  159,  292,  167,
      167,  210,  210,  212,  159,  163,  163,  291,  159,  159,
      159,  289,  267,  163,  288,  285,  163,  167,  267,  210,
      208,  208,  284,  163,  283,  282,  281,  163,  208,  163,
      166,  208,  166,  166,  271,  213,  213,  270,  208,  269,

      166,  166,  208,  166,  208,  268,  216,  216,  252,  252,
      166,  209,  209,  213,  166,  166,  166,  216,  266,  209,
      209,  251,  251,  265,  216,  264,  252,  279,  279,  251,
      253,  253,  262,  209,  209,  209,  279,  280,  280,  253,
      261,  253,  260,  251,  259,  251,  257,  254,  253,  247,
      279,  245,  242,  253,  241,  280,  315,  315,  315,  315,
      315,  315,  315,  315,  316,  316,  316,  316,  316,  316,
      316,  316,  317,  317,  317,  317,  317,  317,  317,  317,
      318,  318,  318,  318,  318,  318,  318,  318,  319,  319,
      319,  320,  320,  321,  239,  238,  321,  321,  321,  321,

      321,  322,  322,  322,  322,  237,  322,  322,  322,  323,
      236,  323,  235,  323,  323,  323,  323,  324,  324,  234,
      233,  232,  231,  229,  227,  226,  225,  224,  223,  222,
      220,  219,  217,  215,  204,  203,  202,  199,  197,  196,
      195,  194,  193,  192,  191,  190,  188,  187,  186,  185,
      183,  182,  180,  179,  178,  177,  176,  174,  173,  172,
      171,  131,  130,  129,  127,  124,  123,  122,  120,  119,
      118,  117,  116,  115,  114,  113,  111,  110,  109,  108,
      107,  105,  104,  102,   95,   78,   73,   65,   55,   53,
       50,   46,   45,   39,   38,   33,   23,   17,   15,   13,

       11,    8,    7,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[132] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "sample.l"




#line 25 "sample.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include "ParseNumbers.h"
#include "parser.tab.h"
#pragma warning(disable : 4996)
#line 671 "sample.flex.cpp"
#line 672 "sample.flex.cpp"

#define INITIAL 0
#define CONST_STRING 1
#define MULTILINE_COMMENT 2
#define ONELINE_COMMENT 3
#define CHAR 4

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 34 "sample.l"



#line 38 "sample.l"
int64_t int_number;
double real_number;
int int_buffer;
char buffer[1000];
char buf_char[2];


#line 817 "sample.flex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 315 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 314 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 45 "sample.l"
{ printf("(%s) - Found KW_ABSTRACT\n", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "sample.l"
{ printf("(%s) - Found KW_VAL\n", yytext); return VAL; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "sample.l"
{ printf("(%s) - Found KW_CASE\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 48 "sample.l"
{ printf("(%s) - Found KW_CATCH\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 49 "sample.l"
{ printf("(%s) - Found KW_CLASS\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 50 "sample.l"
{ printf("(%s) - Found KW_DEF\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 51 "sample.l"
{ printf("(%s) - Found KW_do\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 52 "sample.l"
{ printf("(%s) - Found KW_ELSE\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 53 "sample.l"
{ printf("(%s) - Found KW_EXTENDS\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 54 "sample.l"
{ printf("(%s) - Found KW_FALSE\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 55 "sample.l"
{ printf("(%s) - Found KW_FOR\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 56 "sample.l"
{ printf("(%s) - Found KW_FINAL\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 57 "sample.l"
{ printf("(%s) - Found KW_FINALLY\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 58 "sample.l"
{ printf("(%s) - Found KW_forSome\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 59 "sample.l"
{ printf("(%s) - Found KW_IF\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 60 "sample.l"
{ printf("(%s) - Found KW_IMPLICIT\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 61 "sample.l"
{ printf("(%s) - Found KW_IMPORT\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 62 "sample.l"
{ printf("(%s) - Found KW_LAZY\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 63 "sample.l"
{ printf("(%s) - Found KW_MATCH\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 64 "sample.l"
{ printf("(%s) - Found KW_NEW\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 65 "sample.l"
{ printf("(%s) - Found KW_NULL\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 66 "sample.l"
{ printf("(%s) - Found KW_OBJECT\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 67 "sample.l"
{ printf("(%s) - Found KW_OVERRIDE\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 68 "sample.l"
{ printf("(%s) - Found KW_PACKAGE\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 69 "sample.l"
{ printf("(%s) - Found KW_PRIVATE\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 70 "sample.l"
{ printf("(%s) - Found KW_PROTECTED\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 71 "sample.l"
{ printf("(%s) - Found KW_PRINT\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 72 "sample.l"
{ printf("(%s) - Found KW_PRINTLN\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 73 "sample.l"
{ printf("(%s) - Found KW_PRINTF\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 74 "sample.l"
{ printf("(%s) - Found KW_RETURN\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 75 "sample.l"
{ printf("(%s) - Found KW_SEALED\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 76 "sample.l"
{ printf("(%s) - Found KW_SUPER\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 77 "sample.l"
{ printf("(%s) - Found KW_THIS\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 78 "sample.l"
{ printf("(%s) - Found KW_THROW\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 79 "sample.l"
{ printf("(%s) - Found KW_TRAIT\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 80 "sample.l"
{ printf("(%s) - Found KW_TRUE\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 81 "sample.l"
{ printf("(%s) - Found KW_TRY\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 82 "sample.l"
{ printf("(%s) - Found KW_TYPE\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 83 "sample.l"
{ printf("(%s) - Found KW_VAR\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 84 "sample.l"
{ printf("(%s) - Found KW_WHILE\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 85 "sample.l"
{ printf("(%s) - Found KW_WITH\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 86 "sample.l"
{ printf("(%s) - Found KW_YIELD\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 89 "sample.l"
{buffer[0]=0; BEGIN(CONST_STRING);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 90 "sample.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 91 "sample.l"

	YY_BREAK
case 46:
YY_RULE_SETUP
#line 92 "sample.l"
{strcat(buffer, "\\");}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 93 "sample.l"
{strcat(buffer, "\b");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 94 "sample.l"
{strcat(buffer, "\n");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 95 "sample.l"
{strcat(buffer, "\t");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 96 "sample.l"
{strcat(buffer, "\r");}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 97 "sample.l"
{strcat(buffer, "\"");}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 98 "sample.l"
{strcat(buffer, "\'");}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 99 "sample.l"
{ 
    unsigned int unicode_value = strtol(yytext + 2, NULL, 16); // Преобразуем шестнадцатеричное значение в целое число
    if (unicode_value >= 0 && unicode_value <= 255) { // Проверяем диапазон
        buf_char[0] = (wchar_t)unicode_value; // Присваиваем его буферу
        buf_char[1] = 0; // Завершаем строку
        strcat(buffer, buf_char); // Конкатенируем в буфер
    } else {
        printf("Error: Unicode value is out of range (0000-0255)\n");
    }
}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 109 "sample.l"
{printf("(%s) - Found NOT_ESCAPED_SLASH_N\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(CONST_STRING):
#line 110 "sample.l"
{printf("(%s) - Found ERROR_STRING\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 111 "sample.l"
{printf("(%s) - Found NOT_ESCAPED_SLASH\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 112 "sample.l"
{printf("(%s) - Found CONST_STRING\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 114 "sample.l"
{buffer[0]=0; BEGIN(CHAR);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 115 "sample.l"
{
    yytext[strlen(yytext)-1] = '\0'; // Удаляем одинарную кавычку в конце
    wchar_t buf_char[1]; // Буфер для хранения символа Unicode
    unsigned int unicode_value = strtol(yytext + 2, NULL, 16); // Преобразуем шестнадцатеричное значение в целое число

    // Проверяем, находится ли значение в диапазоне от 0 до 255
    if (unicode_value >= 0 && unicode_value <= 255) {
        buf_char[0] = (wchar_t)unicode_value; // Присваиваем его буферу
        printf("(%lc) - Found CHAR\n", buf_char[0]); // Выводим символ
    } else {
        printf("Error: Unicode value is out of range (0000-0255)\n");
    }

    BEGIN(INITIAL);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 130 "sample.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 131 "sample.l"
{strcat(buffer, "\\");}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 132 "sample.l"
{strcat(buffer, "\b");}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 133 "sample.l"
{strcat(buffer, "\n");}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 134 "sample.l"
{strcat(buffer, "\t");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 135 "sample.l"
{strcat(buffer, "\r");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 136 "sample.l"
{strcat(buffer, "\"");}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 137 "sample.l"
{strcat(buffer, "\'");}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 138 "sample.l"
{printf("(%s) - Found NOT_ESCAPED_SLASH_N\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 139 "sample.l"
{printf("(%s) - Error CHAR\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 140 "sample.l"
{
if(strlen(buffer)==1){
printf("(%s) - Found CHAR\n", buffer); BEGIN(INITIAL);
}else{
printf("(%s) - Error CHAR\n", buffer); BEGIN(INITIAL);
}
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 148 "sample.l"
{buffer[0]=0; BEGIN(MULTILINE_COMMENT);}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 149 "sample.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 150 "sample.l"
{strcat(buffer, "*");}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 151 "sample.l"
{strcat(buffer, "/");}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 152 "sample.l"
{ printf("(%s) - Error MULTILINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 153 "sample.l"
{printf("(%s) - Found MULTILINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 155 "sample.l"
{buffer[0]=0; BEGIN(ONELINE_COMMENT);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 156 "sample.l"
{strcat(buffer, yytext);}
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 157 "sample.l"
{printf("(%s) - Found ONELINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(ONELINE_COMMENT):
#line 158 "sample.l"
{printf("(%s) - Found ONELINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 161 "sample.l"
{ printf("(%s) - Found PLUS_OPERATOR\n", yytext); return '+';}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 162 "sample.l"
{ printf("(%s) - Found MINUS_OPERATOR\n", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 163 "sample.l"
{ printf("(%s) - Found MUL_OPERATOR\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 164 "sample.l"
{ printf("(%s) - Found MOD_OPERATOR\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 165 "sample.l"
{ printf("(%s) - Found MOD_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 166 "sample.l"
{ printf("(%s) - Found EXP_OPERATOR\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 167 "sample.l"
{ printf("(%s) - Found EXP_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 168 "sample.l"
{ printf("(%s) - Found DIV_OPERATOR\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 169 "sample.l"
{ printf("(%s) - Found PLUS_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 170 "sample.l"
{ printf("(%s) - Found MINUS_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 171 "sample.l"
{ printf("(%s) - Found MUL_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 172 "sample.l"
{ printf("(%s) - Found DIV_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 173 "sample.l"
{ printf("(%s) - Found LESS_OR_EQUAL_OPERATOR\n", yytext); return LESS_OR_EQUAL_OPERATOR;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 174 "sample.l"
{ printf("(%s) - Found LEFTSHIFT_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 175 "sample.l"
{ printf("(%s) - Found RIGHTSHIFT_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 176 "sample.l"
{ printf("(%s) - Found MORE_OR_EQUAL_OPERATOR\n", yytext); return MORE_OR_EQUAL_OPERATOR;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 177 "sample.l"
{ printf("(%s) - Found LESS_OPERATOR\n", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 178 "sample.l"
{ printf("(%s) - Found MORE_OPERATOR\n", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 179 "sample.l"
{ printf("(%s) - Found NOT_EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 180 "sample.l"
{ printf("(%s) - Found ASSIGNMENT_OPERATOR\n", yytext); return '=';}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 181 "sample.l"
{ printf("(%s) - Found CIRCUMFLEX\n", yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 184 "sample.l"
{ printf("(%s) - Found EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 185 "sample.l"
{ printf("(%s) - Found NOT_OPERATOR\n", yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 186 "sample.l"
{ printf("(%s) - Found OR_OPERATOR\n", yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 187 "sample.l"
{ printf("(%s) - Found AND_OPERATOR\n", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 189 "sample.l"
{ printf("(%s) - Found BITWISE_AND_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 190 "sample.l"
{ printf("(%s) - Found BITWISE_EX_OR_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 191 "sample.l"
{ printf("(%s) - Found BITWISE_IN_OR_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 192 "sample.l"
{ printf("(%s) - Found BITWISE_OR_OPERATOR\n", yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 193 "sample.l"
{ printf("(%s) - Found BITWISE_LEFTSHIFT_OPERATOR\n", yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 194 "sample.l"
{ printf("(%s) - Found BITWISE_RIGHTSHIFT_OPERATOR\n", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 195 "sample.l"
{ printf("(%s) - Found BITWISE_onesCOMPLEMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 196 "sample.l"
{ printf("(%s) - Found BITWISE_RIGHTSHIF_ZERO_OPERATOR\n", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 198 "sample.l"
{ printf("(%s) - Found TUPLE\n", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 200 "sample.l"
{ printf("(%s) - Found SQUARE_BRACKET\n", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 201 "sample.l"
{ printf("(%s) - Found SQUARE_BRACKET\n", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 202 "sample.l"
{ printf("(%s) - Found ROUND_BRACKET\n", yytext); return '(';}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 203 "sample.l"
{ printf("(%s) - Found ROUND_BRACKET\n", yytext); return ')';}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 204 "sample.l"
{ printf("(%s) - Found BRACE\n", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 205 "sample.l"
{ printf("(%s) - Found BRACE\n", yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 206 "sample.l"
{ printf("(%s) - Found SEMICOLON\n", yytext); return ';';}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 207 "sample.l"
{ printf("(%s) - Found COMMA\n", yytext); return ',';}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 208 "sample.l"
{ printf("(%s) - Found COLON\n", yytext); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 209 "sample.l"
{ printf("(%s) - Found DOT\n", yytext); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 210 "sample.l"
{ printf("(%s) - Found AMPERSAND\n", yytext); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 215 "sample.l"
{
    parse_integer(&int_number, yytext, 10);
    printf("Line %d: found decimal number: %d\n", yylineno, int_number);
    yylval.int_value = int_number;
    return NUM_10;
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 223 "sample.l"
{
    parse_integer(&int_number, yytext, 16);
    printf("Line %d: found hex number: %d\n", yylineno, int_number);
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 229 "sample.l"
{
    parse_real(&real_number, yytext);
    printf("Line %d: found real number: %f\n", yylineno, real_number);
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 234 "sample.l"
{
    parse_real(&real_number, yytext);
    printf("Line %d: found real exponent number: %f\n", yylineno, real_number);
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 241 "sample.l"
{ 
    yylval.str_value = strdup(yytext);
    printf("(%s) - Found IDENTIFIER\n", yytext); 
    return IDENTIFIER;
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 248 "sample.l"
{ printf("(%s) - Error IDENTIFIER\n", yytext); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 250 "sample.l"
{}
	YY_BREAK
case 129:
/* rule 129 can match eol */
YY_RULE_SETUP
#line 251 "sample.l"
{}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 252 "sample.l"
{}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 253 "sample.l"
ECHO;
	YY_BREAK
#line 1604 "sample.flex.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 315 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 315 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 314);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 253 "sample.l"




