#line 1 "sample.flex.cpp"

#line 3 "sample.flex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext

#include "FlexLexer.h"

inline int yyFlexLexer::yywrap() { return 1; }

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 134
#define YY_END_OF_BUFFER 135
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[324] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  135,  133,  130,  104,   44,   85,  124,   58,
       70,   84,   82,  121,   83,  123,   89,  126,  126,  122,
      120,   98,  101,   99,  125,  116,  117,  102,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  118,  110,  119,  113,   45,
       55,   57,   56,   75,   76,   77,   80,   81,   60,   68,
       69,  134,   72,   70,   73,  100,   86,  106,  107,   87,
       92,   90,   91,  115,  128,   74,   79,   93,    0,  126,
      131,  128,  131,  126,  131,  131,  111,   94,  103,   97,

      112,  125,  108,  125,  125,  125,  125,    7,  125,  125,
      125,  125,  125,   15,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  109,  105,   45,   46,   52,   53,
       47,   48,   49,   51,   50,    0,   75,   78,   60,   66,
       67,   61,   62,   63,   65,   64,    0,   88,    0,  128,
        0,  128,  131,  131,    0,  129,  128,  127,  126,  131,
       95,   96,  114,  125,  125,  125,  125,    6,  125,  125,
      125,  125,   11,  125,  125,  125,   20,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,

      125,   38,  125,    2,   40,  125,  125,  125,   46,    0,
        0,  129,  128,    0,  129,  129,  131,  127,  131,  126,
      125,    3,  125,  125,    8,  125,  125,  125,  125,  125,
      125,   18,  125,   21,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,   34,  125,  125,   37,   39,  125,
       42,  125,    0,    0,  129,  129,    0,  128,  125,    4,
        5,  125,   10,   12,  125,  125,  125,   19,  125,  125,
      125,   27,  125,  125,  125,  125,  125,   33,   35,   36,
       41,   43,    0,    0,  128,    0,  125,  125,  125,  125,
      125,   17,   22,  125,  125,   29,  125,  125,  125,  125,

       30,   32,   54,    0,  125,    9,   13,   14,  125,  125,
       24,   28,   25,  125,  125,   59,    1,   16,   23,  125,
       31,   26,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   25,   26,   25,
       27,   27,   27,   27,   27,   28,   27,   27,   27,   27,
       27,   27,   29,   27,   27,   27,   27,   30,   27,   27,
       31,   32,   33,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   27,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        5,    1,    1,    1,    6,    5,    7,    7,    1,    1,
        1,    1,    1,    7,    7,    7,    8,    8,    8,    8,
        1,    2,    1,    1,    8,    7,    7,    7,    7,    7,
        7,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[342] =
    {   0,
        0,    0,   62,   63,   58,   59,  509,  508,   68,   69,
       70,   75,  510,  513,  513,  487,  513,  486,   74,  513,
      513,   71,  485,  513,   64,   71,   81,   89,  133,  513,
      513,   69,  484,   76,    0,  513,  513,  483,  467,   66,
       68,   58,   76,   84,  467,  466,   81,   85,   75,  461,
       91,   90,  464,   66,  455,  513,   61,  513,  513,    0,
      513,  513,  132,    0,  482,  513,  513,  513,    0,  513,
      513,  148,  513,  513,  513,  513,  513,  513,  513,  475,
      513,  513,  513,  513,  173,  513,  513,  513,  121,    0,
        0,  117,  148,  179,  204,  153,  474,  513,  513,  513,

      132,    0,  513,  442,  122,  458,  452,    0,  439,  437,
      443,  440,  436,    0,  436,  426,  431,  427,  436,  437,
      441,  442,  133,   98,  443,  425,  426,  154,  156,  425,
      160,  431,  420,  433,  513,  513,    0,  176,  513,  513,
      513,  513,  513,  513,  513,    0,    0,  513,    0,  513,
      513,  513,  513,  513,  513,  513,    0,  513,  219,  156,
      192,  221,    0,  236,  199,  240,  226,  197,  267,  252,
      513,  513,  513,  418,  431,  432,  416,    0,  428,  427,
      413,  429,  435,  176,  404,  424,    0,  414,  420,  407,
      412,  215,  403,  417,  400,  407,  413,  399,  401,  406,

      409,    0,  408,    0,    0,  400,  403,  398,  232,    0,
        0,  255,  286,  280,    0,  239,  282,    0,  409,  296,
      391,    0,  399,  388,    0,  391,  399,  391,  387,  392,
      383,    0,  391,    0,  395,  380,  395,  376,  393,  388,
      399,  368,  378,  361,    0,  346,  348,    0,    0,  322,
        0,  322,    0,    0,  513,  303,  301,  312,  324,    0,
        0,  320,    0,  311,  309,  318,  300,    0,  299,  307,
      308,  148,  295,  310,  299,  290,  298,    0,    0,    0,
        0,    0,    0,    0,  315,  328,  297,  281,  264,  282,
      272,    0,    0,  271,  269,    0,  256,  261,  237,  240,

        0,    0,  513,  280,  232,    0,    0,    0,  224,  237,
        0,    0,    0,  236,  223,  513,    0,    0,    0,  220,
        0,    0,  513,  363,  371,  379,  387,  390,  392,  400,
      408,  416,  418,  248,  244,  217,  207,  186,  160,  156,
      138
    } ;

static const flex_int16_t yy_def[342] =
    {   0,
      323,    1,  324,  324,  325,  325,  326,  326,  327,  327,
        1,    1,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  328,  328,  323,
      323,  323,  323,  323,  329,  323,  323,  323,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  323,  323,  323,  323,  330,
      323,  323,  323,  331,  323,  323,  323,  323,  332,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,   29,
      333,  333,  333,  333,  333,  333,  323,  323,  323,  323,

      323,  329,  323,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  323,  323,  330,  323,  323,  323,
      323,  323,  323,  323,  323,  334,  331,  323,  332,  323,
      323,  323,  323,  323,  323,  323,  335,  323,  323,  323,
      323,  323,  333,  333,  323,  333,  333,   95,  333,  333,
      323,  323,  323,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  323,  336,
      337,  323,  323,  323,  333,  166,  333,  333,   95,  169,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  338,  339,  323,  323,  323,  323,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  340,  341,  323,  323,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  323,  323,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  323,  329,  329,  329,  329,
      329,  329,    0,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323
    } ;

static const flex_int16_t yy_nxt[578] =
    {   0,
       14,   14,   15,   16,   17,   18,   19,   20,   21,   14,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   35,   35,   35,   35,   35,   35,
       36,   14,   37,   38,   35,   39,   35,   40,   41,   42,
       43,   35,   35,   44,   35,   35,   45,   46,   47,   48,
       49,   50,   51,   52,   35,   53,   54,   35,   55,   35,
       56,   57,   58,   59,   61,   61,   62,   62,   65,   65,
       70,   70,   73,   66,   66,   71,   71,   73,   74,   75,
       78,   80,  135,   74,   75,   83,   84,   85,   85,   97,
       98,   86,   81,   63,   63,   79,   87,  100,  101,   72,

       72,  105,   88,   89,  109,   90,   90,  107,  132,  133,
      122,  111,  106,   92,   93,  110,   94,  108,   95,  112,
      118,  120,  136,   96,  114,  113,  123,   92,   93,   92,
      125,  115,  128,  194,  138,  119,  139,  162,  162,  140,
      121,  129,  164,  126,  304,  127,   95,   89,  130,   90,
       90,  195,  150,  172,  173,  151,  164,   92,   93,  165,
       94,  165,  303,  141,  166,  166,  284,   96,  142,  169,
      169,   92,   93,   92,  175,  176,  192,  209,  209,  152,
      143,  159,  193,  144,  153,  145,  146,  170,  296,   85,
       85,  200,  283,   89,  297,  159,  154,  198,  159,  155,

      160,  156,  157,  167,  164,  199,  204,  161,   85,   85,
      201,  205,  159,  254,  202,  212,  212,  167,  164,  167,
      168,  168,  230,  253,  218,  231,  161,  168,  168,  168,
      165,  219,  165,  209,  209,  212,  212,  162,  162,  168,
      168,  168,  168,  168,  168,  160,  159,  165,  213,  165,
      211,  164,  166,  166,  210,  214,  166,  166,  322,  160,
      159,  160,  321,  238,  215,  164,  163,  216,  169,  169,
      239,  212,  212,  163,  217,  320,  319,  318,  215,  255,
      215,   89,  256,  169,  169,  317,  170,  316,  315,  257,
      314,  167,  164,  255,  220,  255,  162,  162,  166,  166,

      313,  170,  258,  258,  312,  167,  164,  167,  311,  310,
      160,  159,  163,  163,  214,  309,  217,  212,  212,  212,
      212,  308,  307,  163,  160,  159,  160,  255,  258,  258,
      163,  258,  258,  306,  305,  257,  302,  159,  301,  285,
      159,  255,  300,  255,  258,  258,  286,  299,  298,  295,
      294,  159,  293,  292,  159,  291,  290,  289,  288,  287,
      282,  281,  286,   60,   60,   60,   60,   60,   60,   60,
       60,   64,   64,   64,   64,   64,   64,   64,   64,   67,
       67,   67,   67,   67,   67,   67,   67,   69,   69,   69,
       69,   69,   69,   69,   69,   91,   91,   91,  102,  102,

      137,  280,  279,  137,  137,  137,  137,  137,  147,  147,
      147,  147,  278,  147,  147,  147,  149,  277,  149,  276,
      149,  149,  149,  149,  163,  163,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  219,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  237,  236,  235,
      234,  233,  232,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  208,  207,  206,  203,  197,  126,  196,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  174,  171,  158,  148,  134,  131,

      124,  117,  116,  104,  103,   99,   82,   77,   76,  323,
       68,   68,   13,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323
    } ;

static const flex_int16_t yy_chk[578] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,    5,    6,
        9,   10,   11,    5,    6,    9,   10,   12,   11,   11,
       19,   22,   57,   12,   12,   25,   25,   26,   26,   32,
       32,   27,   22,    3,    4,   19,   27,   34,   34,    9,

       10,   40,   27,   28,   42,   28,   28,   41,   54,   54,
       49,   43,   40,   28,   28,   42,   28,   41,   28,   43,
       47,   48,   57,   28,   44,   43,   49,   28,   28,   28,
       51,   44,   52,  124,   63,   47,   63,   89,   89,   63,
       48,   52,   92,   51,  341,   51,   28,   29,   52,   29,
       29,  124,   72,  101,  101,   72,   92,   29,   29,   93,
       29,   93,  340,   63,   93,   93,  339,   29,   63,   96,
       96,   29,   29,   29,  105,  105,  123,  138,  138,   72,
       63,  160,  123,   63,   72,   63,   63,   96,  272,   85,
       85,  129,  338,   94,  272,  160,   72,  128,   85,   72,

       85,   72,   72,   94,   94,  128,  131,   85,  161,  161,
      129,  131,   85,  337,  129,  165,  165,   94,   94,   94,
       95,   95,  184,  336,  168,  184,  161,   95,   95,   95,
      159,  168,  159,  209,  209,  159,  159,  162,  162,   95,
       95,   95,   95,   95,   95,  162,  162,  164,  162,  164,
      335,  167,  164,  164,  334,  162,  166,  166,  320,  162,
      162,  162,  315,  192,  166,  167,  216,  166,  170,  170,
      192,  212,  212,  216,  166,  314,  310,  309,  166,  212,
      166,  169,  212,  169,  169,  305,  170,  304,  300,  212,
      299,  169,  169,  212,  169,  212,  214,  214,  217,  217,

      298,  169,  213,  213,  297,  169,  169,  169,  295,  294,
      213,  213,  220,  220,  214,  291,  217,  257,  257,  256,
      256,  290,  289,  220,  213,  213,  213,  256,  258,  258,
      220,  285,  285,  288,  287,  257,  277,  258,  276,  258,
      285,  256,  275,  256,  286,  286,  258,  274,  273,  271,
      270,  258,  269,  267,  285,  266,  265,  264,  262,  259,
      252,  250,  286,  324,  324,  324,  324,  324,  324,  324,
      324,  325,  325,  325,  325,  325,  325,  325,  325,  326,
      326,  326,  326,  326,  326,  326,  326,  327,  327,  327,
      327,  327,  327,  327,  327,  328,  328,  328,  329,  329,

      330,  247,  246,  330,  330,  330,  330,  330,  331,  331,
      331,  331,  244,  331,  331,  331,  332,  243,  332,  242,
      332,  332,  332,  332,  333,  333,  241,  240,  239,  238,
      237,  236,  235,  233,  231,  230,  229,  228,  227,  226,
      224,  223,  221,  219,  208,  207,  206,  203,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  191,  190,  189,
      188,  186,  185,  183,  182,  181,  180,  179,  177,  176,
      175,  174,  134,  133,  132,  130,  127,  126,  125,  122,
      121,  120,  119,  118,  117,  116,  115,  113,  112,  111,
      110,  109,  107,  106,  104,   97,   80,   65,   55,   53,

       50,   46,   45,   39,   38,   33,   23,   18,   16,   13,
        8,    7,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[135] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 
    0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "sample.l"





#line 26 "sample.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include "ParseNumbers.h"
#include "parser.tab.h"
#pragma warning(disable : 4996)
#define return_token(t) return t



#line 681 "sample.flex.cpp"
#line 682 "sample.flex.cpp"

#define INITIAL 0
#define CONST_STRING 1
#define MULTILINE_COMMENT 2
#define ONELINE_COMMENT 3
#define CONST_CHAR 4
#define PARENS 5

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 39 "sample.l"



#line 43 "sample.l"
int64_t int_number;
double real_number;
int int_buffer;
static int brace_level;
char buffer[1000];
char buf_char[2];


#line 829 "sample.flex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 324 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 323 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 51 "sample.l"
{ printf("(%s) - Found KW_ABSTRACT\n", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "sample.l"
{ printf("(%s) - Found KW_VAL\n", yytext); return VAL; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "sample.l"
{ printf("(%s) - Found KW_CASE\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 54 "sample.l"
{ printf("(%s) - Found KW_CATCH\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "sample.l"
{ printf("(%s) - Found KW_CLASS\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "sample.l"
{ printf("(%s) - Found KW_DEF\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "sample.l"
{ printf("(%s) - Found KW_do\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "sample.l"
{ printf("(%s) - Found KW_ELSE\n", yytext); return ELSE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "sample.l"
{ printf("(%s) - Found KW_EXTENDS\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "sample.l"
{ printf("(%s) - Found KW_FALSE\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "sample.l"
{ printf("(%s) - Found KW_FOR\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "sample.l"
{ printf("(%s) - Found KW_FINAL\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "sample.l"
{ printf("(%s) - Found KW_FINALLY\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "sample.l"
{ printf("(%s) - Found KW_forSome\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "sample.l"
{ printf("(%s) - Found KW_IF\n", yytext); return IF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "sample.l"
{ printf("(%s) - Found KW_IMPLICIT\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "sample.l"
{ printf("(%s) - Found KW_IMPORT\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "sample.l"
{ printf("(%s) - Found KW_LAZY\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "sample.l"
{ printf("(%s) - Found KW_MATCH\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "sample.l"
{ printf("(%s) - Found KW_NEW\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "sample.l"
{ printf("(%s) - Found KW_NULL\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "sample.l"
{ printf("(%s) - Found KW_OBJECT\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "sample.l"
{ printf("(%s) - Found KW_OVERRIDE\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "sample.l"
{ printf("(%s) - Found KW_PACKAGE\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "sample.l"
{ printf("(%s) - Found KW_PRIVATE\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "sample.l"
{ printf("(%s) - Found KW_PROTECTED\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "sample.l"
{ printf("(%s) - Found KW_PRINT\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "sample.l"
{ printf("(%s) - Found KW_PRINTLN\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "sample.l"
{ printf("(%s) - Found KW_PRINTF\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 80 "sample.l"
{ printf("(%s) - Found KW_RETURN\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 81 "sample.l"
{ printf("(%s) - Found KW_READLINE\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "sample.l"
{ printf("(%s) - Found KW_SEALED\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 83 "sample.l"
{ printf("(%s) - Found KW_SUPER\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 84 "sample.l"
{ printf("(%s) - Found KW_THIS\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 85 "sample.l"
{ printf("(%s) - Found KW_THROW\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 86 "sample.l"
{ printf("(%s) - Found KW_TRAIT\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "sample.l"
{ printf("(%s) - Found KW_TRUE\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 88 "sample.l"
{ printf("(%s) - Found KW_TRY\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 89 "sample.l"
{ printf("(%s) - Found KW_TYPE\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "sample.l"
{ printf("(%s) - Found KW_VAR\n", yytext); return VAR;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 91 "sample.l"
{ printf("(%s) - Found KW_WHILE\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "sample.l"
{ printf("(%s) - Found KW_WITH\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "sample.l"
{ printf("(%s) - Found KW_YIELD\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 96 "sample.l"
{buffer[0]=0; BEGIN(CONST_STRING);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 97 "sample.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 98 "sample.l"

	YY_BREAK
case 47:
YY_RULE_SETUP
#line 99 "sample.l"
{strcat(buffer, "\\");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 100 "sample.l"
{strcat(buffer, "\b");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "sample.l"
{strcat(buffer, "\n");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 102 "sample.l"
{strcat(buffer, "\t");}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 103 "sample.l"
{strcat(buffer, "\r");}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 104 "sample.l"
{strcat(buffer, "\"");}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 105 "sample.l"
{strcat(buffer, "\'");}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 106 "sample.l"
{ 
    unsigned int unicode_value = strtol(yytext + 2, NULL, 16); // Преобразуем шестнадцатеричное значение в целое число
    if (unicode_value >= 0 && unicode_value <= 255) { // Проверяем диапазон
        buf_char[0] = (wchar_t)unicode_value; // Присваиваем его буферу
        buf_char[1] = 0; // Завершаем строку
        strcat(buffer, buf_char); // Конкатенируем в буфер
    } else {
        printf("Error: Unicode value is out of range (0000-0255)\n");
    }
}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 116 "sample.l"
{printf("(%s) - Found NOT_ESCAPED_SLASH_N\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(CONST_STRING):
#line 117 "sample.l"
{printf("(%s) - Found ERROR_STRING\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "sample.l"
{printf("(%s) - Found NOT_ESCAPED_SLASH\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "sample.l"
{printf("(%s) - Found CONST_STRING\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 123 "sample.l"
{buffer[0]=0; BEGIN(CONST_CHAR);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 124 "sample.l"
{
    yytext[strlen(yytext)-1] = '\0'; // Удаляем одинарную кавычку в конце
    wchar_t buf_char[1]; // Буфер для хранения символа Unicode
    unsigned int unicode_value = strtol(yytext + 2, NULL, 16); // Преобразуем шестнадцатеричное значение в целое число

    // Проверяем, находится ли значение в диапазоне от 0 до 255
    if (unicode_value >= 0 && unicode_value <= 255) {
        buf_char[0] = (wchar_t)unicode_value; // Присваиваем его буферу
        printf("(%lc) - Found CHAR\n", buf_char[0]); // Выводим символ
    } else {
        printf("Error: Unicode value is out of range (0000-0255)\n");
    }

    BEGIN(INITIAL);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 139 "sample.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 140 "sample.l"
{strcat(buffer, "\\");}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 141 "sample.l"
{strcat(buffer, "\b");}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 142 "sample.l"
{strcat(buffer, "\n");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 143 "sample.l"
{strcat(buffer, "\t");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 144 "sample.l"
{strcat(buffer, "\r");}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 145 "sample.l"
{strcat(buffer, "\"");}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 146 "sample.l"
{strcat(buffer, "\'");}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 147 "sample.l"
{printf("(%s) - Found NOT_ESCAPED_SLASH_N\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(CONST_CHAR):
#line 148 "sample.l"
{printf("(%s) - Error CHAR\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 149 "sample.l"
{
if(strlen(buffer)==1){
printf("(%s) - Found CHAR\n", buffer); BEGIN(INITIAL);
}else{
printf("(%s) - Error CHAR\n", buffer); BEGIN(INITIAL);
}
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 159 "sample.l"
{ BEGIN(PARENS); brace_level = 1;printf("(%s) - Found CIRCLE_BRACKET\n", yytext); return '('; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 160 "sample.l"
{ brace_level++; }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 161 "sample.l"
{}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 162 "sample.l"
{ brace_level--; printf("(%s) - Found CIRCLE_BRACKET\n", yytext);
if (brace_level == 0) {
BEGIN(INITIAL);  return ')';
} 
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 170 "sample.l"
{buffer[0]=0; BEGIN(MULTILINE_COMMENT);}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 171 "sample.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 172 "sample.l"
{strcat(buffer, "*");}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 173 "sample.l"
{strcat(buffer, "/");}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 174 "sample.l"
{ printf("(%s) - Error MULTILINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 175 "sample.l"
{printf("(%s) - Found MULTILINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 177 "sample.l"
{buffer[0]=0; BEGIN(ONELINE_COMMENT);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 178 "sample.l"
{strcat(buffer, yytext);}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 179 "sample.l"
{printf("(%s) - Found ONELINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(ONELINE_COMMENT):
#line 180 "sample.l"
{printf("(%s) - Found ONELINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 184 "sample.l"
{ printf("(%s) - Found PLUS_OPERATOR\n", yytext); return '+';}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 185 "sample.l"
{ printf("(%s) - Found MINUS_OPERATOR\n", yytext); return '-'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 186 "sample.l"
{ printf("(%s) - Found MUL_OPERATOR\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 187 "sample.l"
{ printf("(%s) - Found MOD_OPERATOR\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 188 "sample.l"
{ printf("(%s) - Found MOD_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 189 "sample.l"
{ printf("(%s) - Found EXP_OPERATOR\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 190 "sample.l"
{ printf("(%s) - Found EXP_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 191 "sample.l"
{ printf("(%s) - Found DIV_OPERATOR\n", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 192 "sample.l"
{ printf("(%s) - Found PLUS_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 193 "sample.l"
{ printf("(%s) - Found MINUS_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 194 "sample.l"
{ printf("(%s) - Found MUL_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 195 "sample.l"
{ printf("(%s) - Found DIV_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 196 "sample.l"
{ printf("(%s) - Found LESS_OR_EQUAL_OPERATOR\n", yytext); return LESS_OR_EQUAL_OPERATOR;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 197 "sample.l"
{ printf("(%s) - Found LEFTSHIFT_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 198 "sample.l"
{ printf("(%s) - Found RIGHTSHIFT_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 199 "sample.l"
{ printf("(%s) - Found MORE_OR_EQUAL_OPERATOR\n", yytext); return MORE_OR_EQUAL_OPERATOR;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 200 "sample.l"
{ printf("(%s) - Found LESS_OPERATOR\n", yytext); return '<'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 201 "sample.l"
{ printf("(%s) - Found MORE_OPERATOR\n", yytext); return '>'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 202 "sample.l"
{ printf("(%s) - Found NOT_EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 203 "sample.l"
{ printf("(%s) - Found ASSIGNMENT_OPERATOR\n", yytext); return '=';}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 204 "sample.l"
{ printf("(%s) - Found CIRCUMFLEX\n", yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 207 "sample.l"
{ printf("(%s) - Found EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 208 "sample.l"
{ printf("(%s) - Found NOT_OPERATOR\n", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 209 "sample.l"
{ printf("(%s) - Found OR_OPERATOR\n", yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 210 "sample.l"
{ printf("(%s) - Found AND_OPERATOR\n", yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 212 "sample.l"
{ printf("(%s) - Found BITWISE_AND_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 213 "sample.l"
{ printf("(%s) - Found BITWISE_EX_OR_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 214 "sample.l"
{ printf("(%s) - Found BITWISE_IN_OR_ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 215 "sample.l"
{ printf("(%s) - Found BITWISE_OR_OPERATOR\n", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 216 "sample.l"
{ printf("(%s) - Found BITWISE_LEFTSHIFT_OPERATOR\n", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 217 "sample.l"
{ printf("(%s) - Found BITWISE_RIGHTSHIFT_OPERATOR\n", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 218 "sample.l"
{ printf("(%s) - Found BITWISE_onesCOMPLEMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 219 "sample.l"
{ printf("(%s) - Found BITWISE_RIGHTSHIF_ZERO_OPERATOR\n", yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 221 "sample.l"
{ printf("(%s) - Found TUPLE\n", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 224 "sample.l"
{ printf("(%s) - Found SQUARE_BRACKET\n", yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 225 "sample.l"
{ printf("(%s) - Found SQUARE_BRACKET\n", yytext); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 226 "sample.l"
{ printf("(%s) - Found BRACE\n", yytext); return '{'; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 227 "sample.l"
{ printf("(%s) - Found BRACE\n", yytext); return '}'; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 228 "sample.l"
{ printf("(%s) - Found SEMICOLON\n", yytext); return ';';}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 229 "sample.l"
{ printf("(%s) - Found COMMA\n", yytext); return ',';}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 230 "sample.l"
{ printf("(%s) - Found COLON\n", yytext); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 231 "sample.l"
{ printf("(%s) - Found DOT\n", yytext); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 232 "sample.l"
{ printf("(%s) - Found AMPERSAND\n", yytext); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 235 "sample.l"
{ 
    yylval.str_value = strdup(yytext);
    printf("(%s) - Found IDENTIFIER\n", yytext); 
    return IDENTIFIER;
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 241 "sample.l"
{
    parse_integer(&int_number, yytext, 10);
    printf("Line %d: found decimal number: %d\n", yylineno, int_number);
    yylval.int_value = int_number;
    return NUM_10;
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 249 "sample.l"
{
    parse_integer(&int_number, yytext, 16);
    printf("Line %d: found hex number: %d\n", yylineno, int_number);
   
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 256 "sample.l"
{
    parse_real(&real_number, yytext);
    printf("Line %d: found real number: %f\n", yylineno, real_number);
  
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 262 "sample.l"
{
    parse_real(&real_number, yytext);
    printf("Line %d: found real exponent number: %f\n", yylineno, real_number);
    
}
	YY_BREAK
case 130:
/* rule 130 can match eol */
YY_RULE_SETUP
#line 269 "sample.l"
{
    if (brace_level == 0 ) {
     printf("Found ENDL \n");
        return ENDL;
    }
}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 277 "sample.l"
{ printf("(%s) - Error IDENTIFIER\n", yytext); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 279 "sample.l"
{}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 280 "sample.l"
{}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 281 "sample.l"
ECHO;
	YY_BREAK
#line 1644 "sample.flex.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PARENS):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 324 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 324 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 323);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 281 "sample.l"




